//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattlePlayer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> WinAmount { get; set; }
        public Nullable<int> DefeatAmount { get; set; }
        public Nullable<double> Rating { get; set; }
    }
}
