//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBattleMVVM {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBattleMVVM.MainWindowRes", typeof(MainWindowRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot field.
        /// </summary>
        internal static string BotField_Lbl {
            get {
                return ResourceManager.GetString("BotField_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy.
        /// </summary>
        internal static string Easy_Lbl {
            get {
                return ResourceManager.GetString("Easy_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your name.
        /// </summary>
        internal static string EnterName_Lbl {
            get {
                return ResourceManager.GetString("EnterName_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на uncorrect name.
        /// </summary>
        internal static string Error_Lbl {
            get {
                return ResourceManager.GetString("Error_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string Exit_Btn {
            get {
                return ResourceManager.GetString("Exit_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game Modes.
        /// </summary>
        internal static string GameModes_Lbl {
            get {
                return ResourceManager.GetString("GameModes_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate fleet.
        /// </summary>
        internal static string GenerateFleet_Btn {
            get {
                return ResourceManager.GetString("GenerateFleet_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string Inform_Btn {
            get {
                return ResourceManager.GetString("Inform_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sea Battle{\n}Version 1.0.0{\n}Developer: Marina Rybalko.
        /// </summary>
        internal static string Inform_message {
            get {
                return ResourceManager.GetString("Inform_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string Language_Btn {
            get {
                return ResourceManager.GetString("Language_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, you are loser &gt;_&lt;.
        /// </summary>
        internal static string Loser_message {
            get {
                return ResourceManager.GetString("Loser_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name_Lbl {
            get {
                return ResourceManager.GetString("Name_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal.
        /// </summary>
        internal static string Normal_Lbl {
            get {
                return ResourceManager.GetString("Normal_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rating.
        /// </summary>
        internal static string Rating_Lbl {
            get {
                return ResourceManager.GetString("Rating_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sea Battle.
        /// </summary>
        internal static string SeaBattle_Lbl {
            get {
                return ResourceManager.GetString("SeaBattle_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ship amount:.
        /// </summary>
        internal static string ShipAmount_Lbl {
            get {
                return ResourceManager.GetString("ShipAmount_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shot amount:.
        /// </summary>
        internal static string ShotAmount_Lbl {
            get {
                return ResourceManager.GetString("ShotAmount_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string Start_Btn {
            get {
                return ResourceManager.GetString("Start_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top Players.
        /// </summary>
        internal static string TopPlayers_Btn {
            get {
                return ResourceManager.GetString("TopPlayers_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Congratulations! You are winner!.
        /// </summary>
        internal static string Winner_message {
            get {
                return ResourceManager.GetString("Winner_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Field.
        /// </summary>
        internal static string YourField_Lbl {
            get {
                return ResourceManager.GetString("YourField_Lbl", resourceCulture);
            }
        }
    }
}
