//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBattleMVVM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBattleMVVM.MainWindowRes", typeof(MainWindowRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot field.
        /// </summary>
        internal static string BotField_Lbl {
            get {
                return ResourceManager.GetString("BotField_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy_Lbl {
            get {
                return ResourceManager.GetString("Easy_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string EnterName_Lbl {
            get {
                return ResourceManager.GetString("EnterName_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncorrect name.
        /// </summary>
        internal static string Error_Lbl {
            get {
                return ResourceManager.GetString("Error_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit_Btn {
            get {
                return ResourceManager.GetString("Exit_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Modes.
        /// </summary>
        internal static string GameModes_Lbl {
            get {
                return ResourceManager.GetString("GameModes_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate fleet.
        /// </summary>
        internal static string GenerateFleet_Btn {
            get {
                return ResourceManager.GetString("GenerateFleet_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Inform_Btn {
            get {
                return ResourceManager.GetString("Inform_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Battle{\n}Version 1.0.0{\n}Developer: Marina Rybalko.
        /// </summary>
        internal static string Inform_message {
            get {
                return ResourceManager.GetString("Inform_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_Btn {
            get {
                return ResourceManager.GetString("Language_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are loser &gt;_&lt;.
        /// </summary>
        internal static string Loser_message {
            get {
                return ResourceManager.GetString("Loser_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_Lbl {
            get {
                return ResourceManager.GetString("Name_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal_Lbl {
            get {
                return ResourceManager.GetString("Normal_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating_Lbl {
            get {
                return ResourceManager.GetString("Rating_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Battle.
        /// </summary>
        internal static string SeaBattle_Lbl {
            get {
                return ResourceManager.GetString("SeaBattle_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship amount:.
        /// </summary>
        internal static string ShipAmount_Lbl {
            get {
                return ResourceManager.GetString("ShipAmount_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot amount:.
        /// </summary>
        internal static string ShotAmount_Lbl {
            get {
                return ResourceManager.GetString("ShotAmount_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start_Btn {
            get {
                return ResourceManager.GetString("Start_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Players.
        /// </summary>
        internal static string TopPlayers_Btn {
            get {
                return ResourceManager.GetString("TopPlayers_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You are winner!.
        /// </summary>
        internal static string Winner_message {
            get {
                return ResourceManager.GetString("Winner_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Field.
        /// </summary>
        internal static string YourField_Lbl {
            get {
                return ResourceManager.GetString("YourField_Lbl", resourceCulture);
            }
        }
    }
}
